### ISSUE TITLE
PHP warnings after update to Piwik 3 and php 7.1

### ISSUE THREAD

**Issue by tuxmaster** [piwik/plugin-SecurityInfo#19]
When I call the security info page, an message is shown, that I report here PHP warnings:
WARNING: /var/www/piwik/html/plugins/SecurityInfo/PhpSecInfo/Test/Test.php(389): Notice - A non well formed numeric value encountered - Piwik 3.0.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

Environment:
PHP 7.1 running in fpm mode.

**Comment by mattab** [comment]
Can you try again the version 3.0.3 of the plugin?

Was fixed in https://github.com/piwik/plugin-SecurityInfo/pull/18and new plugin version was just released now

**Comment by tuxmaster** [comment]
After update from 3.0.2 => 3.0.3 now no error is shown.
Thanks.
