### ISSUE TITLE
Plugin not compatible with Piwik 2.10.0

### ISSUE THREAD

**Issue by webmaster128** [piwik/plugin-SecurityInfo#3]
Hi everyone and thanks for you efford! I am getting an error when using the plugin with Piwik 2.10.0

> Das Plugin SecurityInfo ist nicht kompatibel mit Piwik 2.10.0.

which translates to what I wrote in the title.

Piwik version: 2.10.0
Plugin version: 1.0.5
PHP version: 5.4

Are you planing to release an updated version soon or should I uninstall the plugin?

**Comment by mnapoli** [comment]
Hi! This plugin is maintained by the team, it should be working correctly. Do you have the latest version (of the plugin) installed?

**Comment by webmaster128** [comment]
How do I get the plugin version? When I click on the plugin in the admin area, it says:

> Version 1.0.5
> Schlüsselwörter security, phpsec
> Letzte Aktualisierung 9 Jun 14
> Downloads 15088

Is this *my* version or the latest available version from marketplace?

In the source I can only find the phpsecinfo version:

```
/**
 * a general version string to differentiate releases
 *
 */
define ('PHPSECINFO_VERSION', '0.2.2');

/**
 * a YYYYMMDD date string to indicate "build" date
 *
 */
define ('PHPSECINFO_BUILD', '20080723');
```

**Comment by mnapoli** [comment]
It seems to be the latest version (the list of versions is available here: https://github.com/piwik/plugin-SecurityInfo/releases).

I have installed the plugin on my own Piwik (same versions) and it works without problems.

Could you try reinstalling the plugin?

**Comment by mattab** [comment]
Hi @webmaster128 
you can see your currently installed plugin version in the Admin Manage plugin screen. If you still have an issue using latest version please reopen

**Comment by webmaster128** [comment]
Reinstalling fixed the problem. I did not find the version info because it was `(vunknown)`. There must have been an update issue during my Piwik installation lifespan. Thanks anyways!
